treat C1001 (internal compiler error) as system error
Error C1001 may be caused by bugs in the compiler, but most of the time it
is a sign of faulty hardware. We do not want a single malfunctioning host
to cause all compilations to fail, so treat these as system errors.