Fix missing include compile error on linux.
The line #include <sys/uio.h> is also needed on linux, otherwise we get:
error: ‘writev’ was not declared in this scope