From P4 mainline: Fix unsafe caching of PCH with MSVC
[Note] Cache version has changed : Existing cache entries will be
ignored
[Fix] Prevent MSVC Error C1382 caused by retrieving an .obj and .pch
which are mismatched due to multiple machines partially populating the
cache
- If one machine populated the cache (PCH + PCH User), and a second
machine populated the cache (PCH only) then retrieving from the cache
could result in the new PCH plus the old PCH User, causing error C1382:
"the PCH file 'file' has been rebuilt since 'obj' was generated. Please
rebuild this object"
- We were hashing the filename instead of the contents of the PCH object
when generating the PCH key
- This could also have been unsafe if multiple users were compiling
unrelated objects which happened to have the same path